style = "sciml"
margin = 80
remove_extra_newlines = true
always_use_return = true
trailing_comma = false
join_lines_based_on_source = true
yas_style_nesting = true
always_for_in = true
annotate_untyped_fields_with_any = true
normalize_line_endings = "unix"
