name: CI

on:
  push:
    branches:
      - dev
    tags:
      - 'v*'
  pull_request:

jobs:
  phylo-tests:
    runs-on: ${{ matrix.os }}
    continue-on-error: false
    strategy:
      matrix:
        julia-version:
          - '1.6'
          - '1'
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
        arch:
          - x64
          - arm64
        r-testing:
          - ${{ true }}
          - ${{ false }}
        exclude:
          - os: macOS-latest
            arch: x64
          - os: ubuntu-latest
            arch: arm64
          - os: windows-latest
            arch: arm64
          - os: ubuntu-latest
            r-testing: ${{ true }}
          - os: windows-latest
            r-testing: ${{ true }}
          - os: macOS-latest
            r-testing: ${{ false }}
      fail-fast: false
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up julia
      uses: julia-actions/setup-julia@v2
      with:
        version: ${{ matrix.julia-version }}
        arch: ${{ matrix.arch }}
    - name: Install R
      if: ${{ matrix.r-testing }}
      uses: r-lib/actions/setup-r@v2
    - name: Install ape
      if: ${{ matrix.r-testing }}
      run: |
        install.packages("ape", repos="http://cran.r-project.org")
      shell: R --vanilla --file={0}
    - name: Cache
      uses: julia-actions/cache@v1
    - name: Build package
      uses: julia-actions/julia-buildpkg@v1
    - name: Running
      uses: julia-actions/julia-runtest@v1
    - name: Process coverage
      uses: julia-actions/julia-processcoverage@v1
    - name: Codecov
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        verbose: true
